# Generated by Django 5.1 on 2024-09-04 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0003_student_assigned_academic_year"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="assigned_academic_year",
        ),
    ]
