# Generated by Django 5.1 on 2024-09-05 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_course_code"),
        ("students", "0004_remove_student_assigned_academic_year"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="course",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="course_attendance",
                to="courses.course",
            ),
        ),
    ]
