# Generated by Django 5.1 on 2024-09-27 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
        ('courses', '0002_course_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='assigned_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='classes.class'),
        ),
    ]
